import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "@/app/utils/lenis"
import NavForPageTransition from "./Components/NavForPageTransition";
import PageTransition from "./Animations/PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactLenis>
      <body
        className={`antialiased`}
      >
        <PageTransition>
        <NavForPageTransition />
        {children}
        </PageTransition>
      </body>
      </ReactLenis>
    </html>
  );
}
